[phases.setup]
aptPkgs = [
  "chromium",
  "libx11-xcb1",
  "libxcomposite1",
  "libxcursor1",
  "libxi6",
  "libxtst6",
  "libnss3",
  "libcups2",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libatk1.0-0",
  "libasound2",
  "libpangocairo-1.0-0",
  "libatk-bridge2.0-0",
  "libgtk-3-0",
  "libdrm2"
]
